---
- hosts: all

  tasks:

# Username of regular username
# https://stackoverflow.com/a/58916467
  - name: Run whoami without become for regular username
    command: whoami
    changed_when: false
    become: false
    register: whoami

  - name: Set a fact with the user name.
    set_fact:
      login_user: "{{ whoami.stdout }}"

  - name: Install acl for change ansible users
    become: true
    ansible.builtin.apt:
      pkg:
        - acl
      update_cache: yes

# GRUB
# https://github.com/AdisonCavani/distro-grub-themes

  - name: Grub look theme
    ansible.builtin.git:
      repo: https://github.com/AdisonCavani/distro-grub-themes.git
      dest: ~/.gc/distro-grub-themes

  - name: Install grub theme and plymouth theme, configure it
    block:
  
      - name: Create a folder for grub theme
        ansible.builtin.file:
          path: /boot/grub/themes/
          state: directory
          mode: '0755'

      - name: Copy grub theme to grub folder
        ansible.builtin.copy:
          src: ~/.gc/distro-grub-themes/customize/ubuntu/
          dest: /boot/grub/themes

      - name: Adjust grub display resolution
        ansible.builtin.lineinfile:
          path: /etc/default/grub
          regexp: '#GRUB_GFXMODE=640x480'
          line: GRUB_GFXMODE=2560x1440
          backup: yes

      - name: Adjust grub display time
        ansible.builtin.lineinfile:
          path: /etc/default/grub
          regexp: 'GRUB_TIMEOUT=0'
          line: GRUB_TIMEOUT=4

      - name: Add path of theme to grub configure
        ansible.builtin.blockinfile:
          path: /etc/default/grub      
          block: |

            # Ubuntu grub theme
            GRUB_THEME=/boot/grub/themes/theme.txt

      - name: Show grub theme
        ansible.builtin.lineinfile:
          path: /etc/default/grub
          regexp: 'GRUB_TIMEOUT_STYLE=hidden'
          line: GRUB_TIMEOUT_STYLE=menu

      - name: Show splash screen
        ansible.builtin.lineinfile:
          path: /etc/default/grub
          regexp: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
          line: GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3 rd.systemd.show_status=auto rd.udev.log_level=3 splash"
      
      - name: Hide any kernel messages from the console
        ansible.builtin.blockinfile:
          path: /etc/sysctl.d/20-quiet-printk.conf
          create: yes      
          block: |

            # Hide any kernel messages from the console
            kernel.printk = 3 3 3 3

      - name: Update Grub config file
        ansible.builtin.shell: update-grub2

      - name: Install a plymouth (splash screen) theme
        ansible.builtin.apt:
          pkg:
          - plymouth-themes 
          update_cache: yes

      - name: Update initial ramfs for new plymouth theme
        ansible.builtin.shell: update-initramfs -u 

    become: true

# Xorg
  - name: Install Xorg 
    become: true 
    ansible.builtin.apt:
      pkg:
        - xorg
      update_cache: yes

# Lightdm Display Manager

  - name: Install Lightdm 

    block:

      - name: Install a lightdm dependiences
        ansible.builtin.apt:
          pkg:
            - lightdm
            - lightdm-gtk-greeter
            - lightdm-gtk-greeter-settings
          update_cache: yes

      - name: Enable lightdm service
        ansible.builtin.service:
          name: lightdm.service
          enabled: yes

    become: true          
      
# i3-gaps
# https://stackoverflow.com/a/73805885
  - name: Install i3-gaps 

    block:

      - name: Download Regolith public key
        ansible.builtin.get_url:
          url: https://regolith-desktop.org/regolith.key
          dest: /etc/apt/trusted.gpg.d/regolith.asc

      - name: Register Regolith public key to local apt
        ansible.builtin.apt_repository:
          repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/regolith.asc] https://regolith-desktop.org/release-ubuntu-jammy-amd64 {{ ansible_distribution_release }} main"
          state: present
          update_cache: yes

      - name: Install i3-gaps
        ansible.builtin.apt:
          pkg:
            - i3-gaps
          update_cache: yes
          
    become: true

# Linux firmware
  - name: Install Drivers 

    block:

    - name: Install Linux firmware, ubuntu drivers 
      ansible.builtin.apt:
        pkg:
          - linux-firmware
          - ubuntu-drivers-common
        update_cache: yes

    - name: Autoinstall discovered ubuntu drivers
      ansible.builtin.shell: ubuntu-drivers autoinstall
    
    become: true
