---

- hosts: all

  tasks:

#############################################################################################################

# Security

#############################################################################################################

# UFW firewall

  - name: Install firewall

    block:

      - name: Allow incoming policy if virtual mashine detected
        community.general.ufw:
          direction: incoming
          policy: allow

      - name: Allow ssh policy if virtual mashine detected
        community.general.ufw:
          rule: limit
          port: ssh
          proto: tcp

    become: true

#############################################################################################################

# Dotfiles

#############################################################################################################

  - name: Copy screen layout config for Virtualbox to proper folder
    ansible.builtin.copy:
      src: ~/.gc/dotfiles/screenlayout/virtualbox.sh
      dest: ~/.screenlayout
      mode: '0744'

#############################################################################################################

# Last commands before restart

#############################################################################################################

  - name: Delete any leftover temporary files
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - ~/.config/i3/scripts/workspaces
      - ~/.config/polybar/cuts/config.ini

  - name: Copy polybar config to to proper folder
    ansible.builtin.copy:
      src: ~/.config/polybar/cuts/config-virtualbox.ini
      dest: ~/.config/polybar/cuts/config.ini
      mode: '0644'
